DROP TABLE IF EXISTS _user CASCADE;
DROP TABLE IF EXISTS book CASCADE;
DROP TABLE IF EXISTS review;


CREATE TABLE _user (
    id SERIAL PRIMARY KEY ,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE book (
    id SERIAL PRIMARY KEY,
    isbn TEXT NOT NULL,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    year INTEGER NOT NULL
);

CREATE TABLE review (
    id SERIAL PRIMARY KEY,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    book_id INTEGER NOT NULL,
    FOREIGN KEY (author_id) REFERENCES _user (id),
    FOREIGN KEY (book_id) REFERENCES book (id)
);
